### ISSUE TITLE
Feedback on the ski area display table

### ISSUE THREAD

**Issue by joshimmel** [dhimmel/openskistats#6]
1. **Hover Icon for Table Items**  
   Table items should have an info icon that, when hovered over, explains the meaning and perhaps the formula used to derive the value.

2. **Spacing Convention for Units**  
   Convention for units should be a space after the numeric values (e.g., `320 m` vs `320m`).

3. **Search Bars for Numeric Items**  
   The current search bars for numeric items are a bit confusing as-is. Showing nearest values in the category could be helpful (e.g., to find mountains with approximately 1000 m vertical rather than only those above a threshold). Alternatively, sorting by highest to lowest could provide a more intuitive experience.

4. **Hover Summary for Rose Plot**  
   It would be nice to hover over the rose plot and see a summary of the data contributing to each "petal."

5. **Clickable "Ski Area Orientations" Header**  
   Suggest making the "Ski Area Orientations" header clickable to refresh the page or remove filters. Adding a subtitle with descriptive text might also be useful.

6. **Data Citation at Page Bottom**  
   Consider citing data derived from OpenSkiMap and any applicable Creative Commons license in light grey text at the bottom of the page.

7. **Increase Max Items Per Page**  
   Suggest changing the max items per page from 10 to 100, as low data per page reduces engagement. Continuous scroll would also be ideal if feasible.

8. **Repositioning for Orientations**  
   Since "Orientations" is central to this project, consider positioning it further left. However, on a laptop screen, the layout may be limited, while it should fit well on a larger monitor. And I do like the rose diagram as the final column.

---

**Comment by dhimmel** [comment]
Great ideas. Will track progress in this comment:

- [ ] Hover Icon for Table Items. column descriptions in cf35aa8de124b3a3d97f27d129f41c4ff9cd54af
- [ ] Spacing Convention for Units. fa56991ab08ec7aff9c25d9336075b7dc074f4e4
- [ ] Search Bars for Numeric Items
- [ ] Hover Summary for Rose Plot
- [ ] Clickable "Ski Area Orientations" Header
- [ ] Data Citation at Page Bottom
- [ ] Increase Max Items Per Page
- [ ] Repositioning for Orientations

**Comment by dhimmel** [comment]
Most feedback has been addressed. The remaining items are not easy or controversial.
